import "./globals.css";

export const metadata = {
  title: "Smiski Unboxing",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
